config/routes.rb
Realtime::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # only accept oauth
  # devise_scope :user do
  #   get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, :only => [:show, :index]
  resources :games
  resources :queues do
    collection do
      get :add
    end
  end
  resources :messages
  resources :matches
  resources :leader_boards


  match 'twilios/call' => 'twilios#call'
  match 'twilio_callbacks/phone' => 'twilio_callbacks#phone'
  match 'pusher/auth' => 'pusher#auth'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :player1, :class_name => "User"
  belongs_to :player2, :class_name => "User"
  
  before_create :set_match_id

  def set_match_id
    self.unique_id = SecureRandom.uuid.gsub("-", "")
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :invitable, :database_authenticatable, :registerable, :confirmable,
         # :recoverable, :rememberable, :trackable, :validatable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at


  def self.find_for_twitter_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:login => data.screen_name).first
      user
    else # Create a user with a stub password. 
      User.create!(:login => data.screen_name, :name => data.name, :password => Devise.friendly_token[0,20]) 
    end
  end
end

app/models/win.rb
class Win < ActiveRecord::Base
  belongs_to :user
  before_create :reset_count

  def reset_count
    self.count = 0
  end

  def text
    user.name
  end

  def value
    count
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :authenticate_user!, :check_matches

  def show
    if @match.player1_id == current_user.id
      @player_id = 1
    else
      @player_id = 2
    end
  end

  private
  def check_matches
    @match = Match.find_by_unique_id params[:id]
    redirect_to queues_path unless @match && (@match.player1_id == current_user.id || @match.player2_id == current_user.id)
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id
      })
      render :json => response
    else
      head :forbidden
    end
  end
end

app/controllers/queues_controller.rb
class QueuesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @messages = Message.order('id desc').limit(10).all
  end

  def add
    # see if someone is already in the queue waiting for 
    # us to be connected
    msg = ApplicationController.messages_queue.pop
    # TODO: hacketihack, if the last message was pushed by myself keep pulling
    while (msg[:payload] != :queue_empty && msg[:payload].to_i == current_user.id)
      msg = ApplicationController.messages_queue.pop
    end

    # Show the user what we got
    if msg[:payload].present? && msg[:payload] != :queue_empty
      match = Match.create(:player1_id => msg[:payload].to_i, :player2_id => current_user.id)
      # redirect_to match_path(:id => match.unique_id)
        Pusher["private-user-#{msg[:payload].to_i}"].trigger('queue_match', {:match_id => match.unique_id })
      render :js => "window.location.href='#{match_path(:id => match.unique_id)}';"
    else
      # Send the message from the form's input box to the "messages"
      # queue, via the nameless exchange.  The name of the queue to
      # publish to is specified in the routing key.
      ApplicationController.nameless_exchange.publish current_user.id,
        :key => "messages"
      # Notify the user that we published.
      render :js => "$('#waiting').toggle();$('#add_to_queue').toggle();"

    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leader_boards_helper.rb
module LeaderBoardsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/queues_helper.rb
module QueuesHelper
end

app/helpers/twilios_helper.rb
module TwiliosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<h1>Pong.</h1>
<table>
  <caption>Scores</caption>
  <thead>
    <tr>
      <th class="player1">Player 1</th>
      <th class="player2">Player 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="score_player1"></td>
      <td id="score_player2"></td>
    </tr>
  </tbody>
</table>
<canvas id="pong" width="800" height="600">
<p>
Upgrade your browser!
</p>
</canvas>
<p>Move mouse up and down to play, click to reset.</p>
<p>
<a href="http://github.com/camelpunch/pong">Source</a> |
<a href="http://blog.andrewbruce.net/pong-in-html5-canvas-yui3-test">Blog Post</a>
</p>
<script type="text/javascript" charset="utf-8" src="http://yui.yahooapis.com/3.2.0/build/yui/yui-min.js"></script>
<script>
  Pusher.log = function(msg) {
    if(console && console.log) {
      console.log(msg);
    }
  };

  var pusher = new Pusher("<%= Pusher.key %>");
  var socketId = null;
  pusher.connection.bind('connected', function() {
  });
  pusher.connection.bind('disconnected', function() {
    socketId = null;
  });
  var channel = pusher.subscribe('private-channel');
  channel.bind('pusher:subscription_succeeded', function(data) {
    socketId = pusher.connection.socket_id;
  });
  channel.bind('message_received', function(data) {
    alert(data.message);
  });

  channel.bind('client-mouse-moved', function(data) {
    /*TODO: check return type of data, but fuck it's 4:30 am i'm not gonna do that now */
    if (state.player == 1){
      window.PONG.paddle2.setY(data["y"]);
    }
    else {
      window.PONG.paddle1.setY(data["y"]);
    }
  });

  function send_position(currentY) {
    if (socketId != null){
      channel.trigger("client-mouse-moved", {y: currentY});
    }
  }

  function init() {
    $('#triggerBtn').click(handleTrigger);
  };

  function handleTrigger() {
    var data = {
      message: 'hello world'
    };

    if( $("#excludeMe").is(':checked') ) {
      data.socket_id = socketId; // pass socket_id parameter to be used by server
    }

    jQuery.ajax({
      url: "/trigger_event",
      type: "post",
      data: data
    });
  };

</script>
<%= javascript_include_tag "pong" %>

app/views/home/index.html.erb
<%= stylesheet_link_tag "radar" %>
<%= javascript_include_tag "radar" %>
<h2>See who's currently playing</h2>
<div id="radar">
  <div class="radar-bezel">
    <div class="radar-shine"></div>
    <div class="radar-background">
      <div id="radar-area"></div>
      <div class="radar- bordertop"></div>
      <div class="radar-borderbottom"></div>
      <div class="radar-shadow"></div>
    </div>
    <div class="radar-border2"></div>
  </div>
</div>

app/views/queues/index.html.erb
<div class="span12">
  <center><h2>Pong waiting room, click below to wait in queue</h2></center>
</div>
<div class="span6">
  <h3>Chat</h3>
  <%= form_tag messages_path, :remote => true do %>
    <%= text_field_tag :message %>
    <%= submit_tag "Send" %>
  <% end %>
  <div class="well" style="overflow:auto; height:200px;">
  <ul id="content" class="unstyled">
    <% @messages.each do |message| %>
      <li><a href='http://twitter.com/<%= message.owner %>'>@<%= message.owner %></a>: <%= message.content %></li>
    <% end -%>
  </ul>
  </div>
</div>
<div class="offset1 span4">
  <div id="add_to_queue">
    <div class="row">
      <%= link_to add_queues_path,:remote=>true do %>
        <%= image_tag "queue.jpg" %>
      <% end -%>
    </div>
    <div class="row">
      <%= link_to "Add to queue", add_queues_path,:remote=>true, :class => "btn" %>
    </div>
  </div>
  <div id="waiting" style="display: none;">
    <h3>Please wait until we find a partner for you.</h3>
  </div>
</div>

<script>
  <%# Pusher.log = function(msg) { %>
  <%#   if(console && console.log) { %>
  <%#     console.log(msg); %>
  <%#   } %>
  <%# }; %>

  var pusher = new Pusher("<%= Pusher.key %>");
  var socketId = null;
  pusher.connection.bind('connected', function() {
  });
  pusher.connection.bind('disconnected', function() {
    socketId = null;
  });
  var channel = pusher.subscribe('ldnrealtime');
  var priv_channel = pusher.subscribe('private-user-<%= current_user.id %>');

  priv_channel.bind('queue_match', function(data) {
    loc = "/matches/" + data.match_id;
    window.location.href = loc ;
  });

  channel.bind('pusher:subscription_succeeded', function(data) {
    socketId = pusher.connection.socket_id;
  });
  channel.bind('message_received', function(data) {
    $("ul#content").prepend('<li>'+data.message+'</li>');
  });

</script>