config/routes.rb
Realtime::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # only accept oauth
  # devise_scope :user do
  #   get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, :only => [:show, :index]
  resources :games
  resources :queues do
    collection do
      get :add
    end
  end
  resources :messages
  resources :matches
  resources :leader_boards


  match 'twilios/call' => 'twilios#call'
  match 'twilio_callbacks/phone' => 'twilio_callbacks#phone'
  match 'pusher/auth' => 'pusher#auth'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :player1, :class_name => "User"
  belongs_to :player2, :class_name => "User"
  
  before_create :set_match_id

  def set_match_id
    self.unique_id = SecureRandom.uuid.gsub("-", "")
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :invitable, :database_authenticatable, :registerable, :confirmable,
         # :recoverable, :rememberable, :trackable, :validatable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at


  def self.find_for_twitter_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:login => data.screen_name).first
      user
    else # Create a user with a stub password. 
      User.create!(:login => data.screen_name, :name => data.name, :password => Devise.friendly_token[0,20]) 
    end
  end
end

app/models/win.rb
class Win < ActiveRecord::Base
  belongs_to :user
  before_create :reset_count

  def reset_count
    self.count = 0
  end

  def text
    user.name
  end

  def value
    count
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id
      })
      render :json => response
    else
      head :forbidden
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leader_boards_helper.rb
module LeaderBoardsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/queues_helper.rb
module QueuesHelper
end

app/helpers/twilios_helper.rb
module TwiliosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to "I am the realtime pusher", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to('Enter queue', queues_path)  %></li>  
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% if Rails.env.development? %>
      <%= link_to('Login', new_user_session_path)  %>  
    <% end -%>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <% if false %>
      <li>
      <%= link_to('Sign up', new_user_registration_path)  %>
      </li>
    <% end -%>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Realtime" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
        <a href="http://github.com/fishman/ldnrealtimehack"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/5d21241b64dc708fcbb701f68f72f41e9f1fadd6/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f7265645f6161303030302e706e67" alt="Fork me on GitHub"></a>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">×</a>
                  <%= msg %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= render :partial => 'shared/gosquared' %>


  </body>
</html>

app/views/layouts/games.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Realtime" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "games", :media => "all" %>
    <script src="http://js.pusher.com/1.10/pusher.min.js"></script>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/matches.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Realtime" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "games", :media => "all" %>
    <script src="http://js.pusher.com/1.11/pusher.min.js"></script>
</script>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= yield %>

    <%= render :partial => 'shared/gosquared' %>
  </body>
</html>

app/views/shared/_gosquared.html.erb
<script type="text/javascript">
  var GoSquared={};
GoSquared.acct = "GSN-643227-Z";
(function(w){
function gs(){
w._gstc_lt=+(new Date); var d=document;
var g = d.createElement("script"); g.type = "text/javascript"; g.async = true; g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(g, s);
}
w.addEventListener?w.addEventListener("load",gs,false):w.attachEvent("onload",gs);
})(window);
</script>